In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
n=9
len(str(n))

1

In [1]:
def complement_nine(n):
    return 10 ** len(str(n)) - 1 - n

# # Test code
print(complement_nine(0)) # 9 
print(complement_nine(9)) # 0 
print(complement_nine(4)) # 5 
print(complement_nine(18)) # 81 
print(complement_nine(40)) # 59 
print(complement_nine(307)) # 692 
print(complement_nine(9142)) # 857 
print(complement_nine(9965)) # 34 

9
0
5
81
59
692
857
34


In [ ]:
a = np.array([[[1,2,3], [4,5,6]],[[0.1,0.2,0.3] ,[0.4,0.5,0.6]]])
b = np.array([[[10,20],[30,40],[50,60]],[[1,2],[3,4],[5,6]]])
np.dot(a,b)

array([[[[220. , 280. ],
         [ 22. ,  28. ]],

        [[490. , 640. ],
         [ 49. ,  64. ]]],


       [[[ 22. ,  28. ],
         [  2.2,   2.8]],

        [[ 49. ,  64. ],
         [  4.9,   6.4]]]])

In [ ]:
np.matmul(a,b)

array([[[220. , 280. ],
        [490. , 640. ]],

       [[  2.2,   2.8],
        [  4.9,   6.4]]])

In [ ]:
import tensorflow as tf

In [ ]:
a = tf.constant([[[1,2,3], [4,5,6]],[[0.1,0.2,0.3] ,[0.4,0.5,0.6]]])
b = tf.constant([[[10,20],[30,40],[50,60]],[[1,2],[3,4],[5,6]]],dtype = tf.float32)
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[220.       , 280.       ],
        [490.       , 640.       ]],

       [[  2.2      ,   2.8000002],
        [  4.9      ,   6.4      ]]], dtype=float32)>

In [ ]:
tf.tensordot(a,b,axes=[[2],[1]])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[220.       , 280.       ],
         [ 22.       ,  28.       ]],

        [[490.       , 640.       ],
         [ 49.       ,  64.       ]]],


       [[[ 22.       ,  28.       ],
         [  2.2      ,   2.8000002]],

        [[ 49.       ,  64.       ],
         [  4.9      ,   6.4      ]]]], dtype=float32)>

In [ ]:
a = np.array([[0,1,2],[3,4,5]])
a.shape

(2, 3)

In [ ]:
np.reshape(a,(3,2))


array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.reshape(a,(3,-1))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.reshape(a,(-1,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.reshape(a,6)


array([0, 1, 2, 3, 4, 5])

In [ ]:
np.transpose(a)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
a= np.array([[1],[2],[3],[4]])
b= np.array([1])
a+b

array([[2],
       [3],
       [4],
       [5]])

In [ ]:
a= np.array([[1,2],[3,4]])
b= np.array([1])
a+b

array([[2, 3],
       [4, 5]])

In [ ]:
a= np.array([[1,2,3],[4,5,6]])
b= np.array([1,2,3])
a+b

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
a= np.array([[1,2],[3,4]])
b= np.array([1])
print(a+b)


[[2 3]
 [4 5]]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/jiho

/content/drive/MyDrive/Colab Notebooks/jiho


In [ ]:
import os
forders = os.listdir('/content/drive/MyDrive/Colab Notebooks/jiho')

# 데이터 불러올라고 경로설정

# 데이터 불러오고 전처리

In [ ]:


data = pd.DataFrame()
for files in forders:
    #print(files)
    df =pd.read_csv(files, encoding='cp949')
    bb = df['Value']
    zz=pd.DataFrame(bb).transpose()
    data = pd.concat([data,zz])
data.reset_index(drop=True, inplace =True)
data =data.truncate(before=0,after=4356,axis=1)
data.insert(len(data.columns),'y',[0,1,1,0,1,1,1,0,1,2,1,1,1,1,2,1,3,1,1,3,1,1,1,1,0,1])
data = data.astype('float')

data = data.dropna(axis='columns')
data



0      1      2      3      4      5      6      7      8      9  ...  \
0   131.0   43.0  116.0   39.0   47.0   38.0   36.0   37.0   43.0  109.0  ...   
1    94.0   30.0   33.0   31.0   33.0   35.0   35.0   31.0   31.0   35.0  ...   
2    37.0   55.0  208.0   44.0   30.0  217.0   35.0   76.0   46.0   44.0  ...   
3    97.0   60.0   42.0  163.0   78.0   67.0   31.0   76.0   60.0   38.0  ...   
4    49.0  423.0   41.0  238.0  359.0   45.0   31.0  332.0  468.0   32.0  ...   
5   107.0   83.0  487.0   30.0   45.0  240.0  166.0   39.0   94.0   40.0  ...   
6    38.0   31.0   35.0   63.0   55.0   31.0   37.0   76.0   52.0   31.0  ...   
7    43.0   72.0   21.0   24.0   91.0   23.0   63.0   40.0   17.0  209.0  ...   
8    90.0  194.0   84.0  133.0   83.0   96.0   79.0   93.0   91.0   77.0  ...   
9    39.0  133.0   32.0  100.0   88.0   29.0  118.0   33.0   26.0   37.0  ...   
10   73.0   53.0   56.0   59.0   43.0   49.0   37.0   60.0   80.0   36.0  ...   
11   71.0   35.0   33.0   65.0   65.0   52.0   57.0   70.0  180.0   70.0  ...   
12   55.0   53.0  360.0   48.0   32.0   82.0   88.0   47.0   73.0  203.0  ...   
13   36.0   51.0   73.0  133.0   67.0  240.0   42.0   66.0   91.0   71.0  ...   
14   42.0   59.0   42.0  202.0  163.0  334.0  214.0   32.0   32.0  218.0  ...   
15  132.0  411.0  144.0   53.0  438.0  473.0  436.0  284.0  402.0  402.0  ...   
16  369.0   67.0  256.0   31.0   69.0  516.0   36.0  172.0   54.0  174.0  ...   
17   40.0  257.0   62.0   44.0   42.0  117.0   43.0  274.0   38.0  280.0  ...   
18  170.0   45.0   30.0   59.0   36.0   28.0   61.0   59.0   32.0   45.0  ...   
19  377.0  150.0  115.0  160.0   55.0   24.0   32.0   65.0   47.0  138.0  ...   
20   57.0   82.0   51.0   18.0   15.0   43.0  443.0  444.0  404.0  440.0  ...   
21  197.0   57.0   68.0  168.0   54.0   59.0   63.0  172.0   64.0   67.0  ...   
22   63.0   80.0   70.0   35.0   73.0   41.0   59.0   31.0   39.0   39.0  ...   
23   38.0   32.0    9.0   29.0   76.0   18.0   31.0   66.0   40.0  133.0  ...   
24   30.0   17.0  171.0   34.0   28.0   38.0   40.0   82.0   63.0   72.0  ...   
25  506.0  516.0  521.0  540.0  546.0  552.0   24.0   57.0   19.0   19.0  ...   

     4347   4348   4349   4350   4351   4352   4353   4354   4355    y  
0    37.0  115.0   35.0   42.0   48.0   43.0   33.0  130.0   34.0  0.0  
1    44.0   34.0   37.0   37.0   37.0   35.0   32.0   34.0   31.0  1.0  
2    57.0   35.0   33.0   41.0  108.0   31.0   39.0   41.0   72.0  1.0  
3    30.0   39.0  152.0   59.0   33.0   49.0   59.0  125.0   36.0  0.0  
4   510.0  282.0   33.0  409.0   41.0  126.0   43.0  264.0  136.0  1.0  
5    37.0  442.0   91.0  113.0  441.0  209.0   33.0  183.0   31.0  1.0  
6    50.0   30.0   50.0   31.0   99.0   33.0   38.0   31.0  141.0  1.0  
7    77.0   19.0  137.0   31.0   61.0   93.0   76.0   24.0   76.0  0.0  
8   194.0   72.0  190.0  201.0  193.0  185.0   72.0  199.0  177.0  1.0  
9    39.0   23.0   31.0   40.0  121.0   16.0   30.0   56.0   89.0  2.0  
10   62.0  168.0   52.0   43.0   58.0   57.0   56.0   49.0   42.0  1.0  
11  170.0   33.0   42.0   59.0   60.0   39.0   65.0   51.0   58.0  1.0  
12   86.0   79.0   40.0   56.0  148.0   61.0   54.0   75.0   79.0  1.0  
13  207.0   94.0   56.0  205.0   71.0   54.0  186.0   30.0   68.0  1.0  
14  342.0   55.0   57.0  289.0  419.0  382.0  550.0   36.0  529.0  2.0  
15   57.0  266.0  309.0  596.0  167.0  320.0   40.0  570.0  411.0  1.0  
16  402.0  151.0   53.0  220.0   66.0  180.0   57.0  317.0  126.0  3.0  
17   39.0  112.0   45.0   43.0   64.0   33.0   52.0   42.0   47.0  1.0  
18   43.0   28.0   73.0   28.0   34.0   49.0   53.0   42.0   42.0  1.0  
19   26.0   24.0   36.0   36.0  134.0   43.0   42.0   28.0   57.0  3.0  
20   39.0   11.0   34.0   31.0   13.0   26.0   11.0   10.0   34.0  1.0  
21  135.0   72.0   64.0   30.0  245.0   35.0   46.0   68.0   39.0  1.0  
22   33.0   85.0   66.0  106.0   33.0   78.0   65.0   71.0  441.0  1.0  
23   19.0   15.0   66.0  101.0  119.0   35.0   40.0   43.0   67.0  1

In [ ]:

from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier,RandomForestClassifier,BaggingClassifier
import sklearn.svm as svm
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix


In [ ]:
print(data['y'].value_counts())

y = data['y']
X = data.drop('y', axis=1)

1.0    18
0.0     4
2.0     2
3.0     2
Name: y, dtype: int64


In [ ]:


rf = RandomForestClassifier(n_estimators=1000, random_state=0)
gb = GradientBoostingClassifier(random_state =0)
mlp = MLPClassifier(hidden_layer_sizes=(100,100), 
                    activation='tanh', solver='lbfgs',
                    batch_size='auto', learning_rate='adaptive', alpha=0.0001,max_iter=1000)
svm_model =svm.SVC(kernel = 'rbf',C=8,gamma =0.1)

clf = BaggingClassifier(base_estimator=mlp, n_estimators=30, random_state=0)
model_name = ["RandomForest","GradientBoosting","MLP","SVM","Bagging"]
models = [rf,gb,mlp,svm_model,clf]
accu =[]
for i in range(len(models)):
    print(model_name[i])
    kkk = []
    for k in range(5):
        X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.1,
                                                    shuffle=True)        
        start = time.time() 
        models[i].fit(X_train,y_train)
        y_pred = models[i].predict(X_test)
        print(y_pred)
        print("훈련 세트 정확도: {:.3f}".format(models[i].score(X_train, y_train)))
        print("테스트 세트 정확도: {:.5f}".format(np.mean(y_pred == y_test))) # 예측 정확도
        kkk.append(np.mean(y_pred == y_test))
        cf = confusion_matrix(y_test, y_pred)
        
        print(cf)
        #sns.heatmap(cf, annot=True)
        plt.show()
        print("time :", time.time() - start)
        print("*****************************")
        print(" ")
    print(model_name[i],np.mean(np.array(kkk)))
    accu.append(np.mean(np.array(kkk)))
    print("************************************************")


RandomForest
[1. 1. 1.]
훈련 세트 정확도: 1.000
테스트 세트 정확도: 0.66667
[[0 1]
 [0 2]]
time : 2.7429070472717285
*****************************
 
[1. 1. 1.]
훈련 세트 정확도: 1.000
테스트 세트 정확도: 1.00000
[[3]]
time : 2.208280563354492
*****************************
 


KeyboardInterrupt: ignored